//! Rust source generation for the target Axum project.
//!
//! Code is built as a `proc_macro2::TokenStream` via `quote!`, parsed with
//! `syn`, and pretty-printed with `prettyplease`. This guarantees
//! syntactically valid, well-formatted output and avoids the fragility of
//! string templates. `Cargo.toml` is the only string-template exception
//! (TOML has no quote-equivalent).
//!
//! See `docs/architecture.md` and `docs/decisions.md`.

use crate::manifest::{Manifest, ServiceUrl};
use crate::routes::{axum_path, HttpMethod, Route, RouteKind};
use anyhow::{Context, Result};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::fs;
use std::path::Path;

/// Emit the full generated project under `dist_dir`.
///
/// `dist/target/` is intentionally preserved between regenerations so cargo
/// can rebuild incrementally — a clean wipe would force a full ~30s rebuild
/// and make `rublocks dev` unusable.
pub fn emit(manifest: &Manifest, dist_dir: &Path) -> Result<()> {
    if dist_dir.exists() {
        let target = dist_dir.join("target");
        for entry in fs::read_dir(dist_dir)? {
            let path = entry?.path();
            if path == target {
                continue;
            }
            if path.is_dir() {
                fs::remove_dir_all(&path)
                    .with_context(|| format!("failed to clean {}", path.display()))?;
            } else {
                fs::remove_file(&path)
                    .with_context(|| format!("failed to clean {}", path.display()))?;
            }
        }
    }
    fs::create_dir_all(dist_dir.join("src"))
        .with_context(|| format!("failed to create {}", dist_dir.display()))?;

    fs::write(dist_dir.join("Cargo.toml"), render_cargo_toml(manifest))?;
    fs::write(dist_dir.join("src").join("main.rs"), render_main_rs(manifest)?)?;
    Ok(())
}

/// Build the generated `Cargo.toml` as a plain string.
///
/// Only services declared in the manifest add their crate to `[dependencies]`,
/// keeping the dist project minimal. `axum`, `tokio`, `anyhow`, `futures-util`
/// are always present (they back the `/health` route, the runtime, error
/// propagation, and the dev-mode SSE stream respectively).
fn render_cargo_toml(manifest: &Manifest) -> String {
    let mut deps = String::from(
        "axum = \"0.8\"\n\
         tokio = { version = \"1\", features = [\"macros\", \"rt-multi-thread\"] }\n\
         anyhow = \"1\"\n\
         futures-util = \"0.3\"\n",
    );
    if manifest.services.postgres.is_some() {
        deps.push_str(
            "sqlx = { version = \"0.8\", default-features = false, features = [\"runtime-tokio\", \"tls-rustls\", \"postgres\"] }\n",
        );
    }
    if manifest.services.redis.is_some() {
        deps.push_str(
            "deadpool-redis = { version = \"0.18\", features = [\"rt_tokio_1\"] }\n",
        );
    }

    format!(
        "# Generated by rublocks. Do not edit by hand.\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [dependencies]\n\
         {deps}",
        name = manifest.name,
    )
}

/// Build the generated `src/main.rs` as a formatted Rust string.
///
/// The output is structured the same way for every project:
///
/// 1. `AppState` struct (fields conditional on declared services).
/// 2. `#[tokio::main] async fn main` — initializes pools, registers routes,
///    enables dev routes if `RUBLOCKS_DEV=1`, then `axum::serve`.
/// 3. The `/health` handler (always present).
/// 4. Dev-mode handlers (always compiled, mounted only when env var set —
///    see `docs/dev-mode.md`).
///
/// The `quote!` macro handles `Option<TokenStream>` interpolation natively:
/// `None` expands to nothing, so the conditional blocks for postgres/redis
/// disappear cleanly when those services are absent.
fn render_main_rs(manifest: &Manifest) -> Result<String> {
    let has_pg = manifest.services.postgres.is_some();
    let has_redis = manifest.services.redis.is_some();

    let pg_field = has_pg.then(|| quote! { pub pg: sqlx::PgPool, });
    let redis_field = has_redis.then(|| quote! { pub redis: deadpool_redis::Pool, });

    let pg_init = manifest.services.postgres.as_ref().map(|svc| {
        let url = url_expr(&svc.url);
        quote! {
            let pg = sqlx::PgPool::connect(&#url).await?;
        }
    });
    let redis_init = manifest.services.redis.as_ref().map(|svc| {
        let url = url_expr(&svc.url);
        quote! {
            let redis = deadpool_redis::Config::from_url(&#url)
                .create_pool(Some(deadpool_redis::Runtime::Tokio1))?;
        }
    });

    let pg_state = has_pg.then(|| quote! { pg, });
    let redis_state = has_redis.then(|| quote! { redis, });

    let user_owns_root_get = manifest
        .routes
        .iter()
        .any(|r| r.method == HttpMethod::Get && r.path == "/");
    let dev_index_fn = (!user_owns_root_get).then(|| {
        let html = render_dev_index_html(&manifest.name);
        quote! {
            async fn dev_index() -> axum::response::Html<&'static str> {
                axum::response::Html(#html)
            }
        }
    });
    let dev_root_route = (!user_owns_root_get).then(|| {
        quote! { router = router.route("/", get(dev_index)); }
    });

    let method_imports = used_method_imports(&manifest.routes);
    let route_registrations = manifest.routes.iter().map(render_route_registration);
    let route_handlers = manifest.routes.iter().map(render_route_handler);

    let tokens = quote! {
        use axum::{routing::{#(#method_imports),*}, Router};

        #[derive(Clone)]
        pub struct AppState {
            #pg_field
            #redis_field
        }

        #[tokio::main]
        async fn main() -> anyhow::Result<()> {
            #pg_init
            #redis_init

            let state = AppState {
                #pg_state
                #redis_state
            };

            let mut router = Router::new().route("/health", get(health));

            #(#route_registrations)*

            if std::env::var("RUBLOCKS_DEV").is_ok() {
                #dev_root_route
                router = router
                    .route("/__rublocks/livereload.js", get(dev_snippet))
                    .route("/__rublocks/events", get(dev_events));
                eprintln!("rublocks: dev endpoints enabled at /__rublocks/*");
            }

            let app = router.with_state(state);

            let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await?;
            println!("rublocks app listening on http://0.0.0.0:3000");
            axum::serve(listener, app).await?;
            Ok(())
        }

        async fn health() -> &'static str {
            "ok"
        }

        #(#route_handlers)*

        #dev_index_fn

        async fn dev_snippet() -> impl axum::response::IntoResponse {
            (
                [(axum::http::header::CONTENT_TYPE, "application/javascript")],
                LIVERELOAD_JS,
            )
        }

        async fn dev_events() -> axum::response::Sse<
            impl futures_util::Stream<Item = Result<axum::response::sse::Event, std::convert::Infallible>>,
        > {
            let stream = futures_util::stream::pending::<
                Result<axum::response::sse::Event, std::convert::Infallible>,
            >();
            axum::response::Sse::new(stream)
                .keep_alive(axum::response::sse::KeepAlive::default())
        }

        const LIVERELOAD_JS: &str = #LIVERELOAD_JS_SOURCE;
    };

    let file: syn::File = syn::parse2(tokens).context("failed to parse generated tokens")?;
    let body = prettyplease::unparse(&file);
    Ok(format!("// Generated by rublocks. Do not edit by hand.\n\n{body}"))
}

/// Wire one `Route` into the generated Axum router.
///
/// Slice 1 ignores everything past `path`/`method`/`kind` — handlers are
/// stubs that announce their identity. Subsequent slices flesh out template
/// rendering, input parsing, db access, and view/output mapping.
fn render_route_registration(route: &Route) -> TokenStream {
    let path = axum_path(&route.path);
    let handler = format_ident!("route_{}", route.name);
    let method = method_ident(route.method);
    quote! {
        router = router.route(#path, #method(#handler));
    }
}

fn render_route_handler(route: &Route) -> TokenStream {
    let handler = format_ident!("route_{}", route.name);
    let label = match route.kind {
        RouteKind::Page => format!("rublocks: page route `{}` not yet rendered", route.path),
        RouteKind::Api => format!("rublocks: api route `{}` not yet implemented", route.path),
    };
    quote! {
        async fn #handler() -> &'static str {
            #label
        }
    }
}

fn method_ident(method: HttpMethod) -> proc_macro2::Ident {
    format_ident!("{}", method_name(method))
}

fn method_name(method: HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Delete => "delete",
        HttpMethod::Patch => "patch",
    }
}

/// Build the `axum::routing::{...}` import list, including only methods the
/// generated code actually references. `get` is always present (`/health`).
fn used_method_imports(routes: &[Route]) -> Vec<proc_macro2::Ident> {
    let mut names: std::collections::BTreeSet<&'static str> = std::collections::BTreeSet::new();
    names.insert("get");
    for r in routes {
        names.insert(method_name(r.method));
    }
    names.into_iter().map(|n| format_ident!("{}", n)).collect()
}

/// Translate a `ServiceUrl` into the Rust expression used at startup.
///
/// `Literal` is embedded as-is; `Env` becomes a `std::env::var(...)?` call,
/// so the binary fails fast at startup if the variable is unset.
fn url_expr(url: &ServiceUrl) -> TokenStream {
    match url {
        ServiceUrl::Literal(s) => quote! { #s.to_string() },
        ServiceUrl::Env(var) => quote! { std::env::var(#var)? },
    }
}

/// Render the dev-mode HTML demo page.
///
/// This page is a placeholder served at `GET /` whenever `RUBLOCKS_DEV=1`.
/// It exists so the user has something to load in a browser before any
/// user-defined routes exist, exercising the livereload pipeline end-to-end.
fn render_dev_index_html(app_name: &str) -> String {
    format!(
        "<!DOCTYPE html>\n\
         <html lang=\"en\">\n\
         <head>\n  \
           <meta charset=\"utf-8\">\n  \
           <title>{app_name} \u{2014} rublocks dev</title>\n  \
           <script src=\"/__rublocks/livereload.js\"></script>\n\
         </head>\n\
         <body style=\"font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; color: #222;\">\n  \
           <h1 style=\"margin-bottom: 0.25rem;\">{app_name}</h1>\n  \
           <p style=\"color: #666; margin-top: 0;\">rublocks dev mode</p>\n  \
           <p>Edit <code>main.json</code> and save \u{2014} this page will reload automatically.</p>\n\
         </body>\n\
         </html>\n"
    )
}

/// Browser-side livereload snippet, embedded as a constant in the generated
/// project.
///
/// Protocol: open an `EventSource` to `/__rublocks/events`. On the first
/// successful open, just record `everConnected = true`. On disconnect,
/// retry with a 500ms backoff. Once a reconnect succeeds (server came back
/// after restart), call `location.reload()`. The SSE stream itself never
/// emits payload events — the connect/disconnect cycle is the signal.
const LIVERELOAD_JS_SOURCE: &str = r#"(function () {
  let everConnected = false;
  function connect() {
    const es = new EventSource('/__rublocks/events');
    es.onopen = function () {
      if (everConnected) {
        location.reload();
      }
      everConnected = true;
    };
    es.onerror = function () {
      es.close();
      setTimeout(connect, 500);
    };
  }
  connect();
})();
"#;
