use crate::manifest::{Manifest, ServiceUrl};
use anyhow::{Context, Result};
use proc_macro2::TokenStream;
use quote::quote;
use std::fs;
use std::path::Path;

pub fn emit(manifest: &Manifest, dist_dir: &Path) -> Result<()> {
    if dist_dir.exists() {
        let target = dist_dir.join("target");
        // Preserve `target/` so cargo can do incremental rebuilds across regenerations.
        for entry in fs::read_dir(dist_dir)? {
            let path = entry?.path();
            if path == target {
                continue;
            }
            if path.is_dir() {
                fs::remove_dir_all(&path)
                    .with_context(|| format!("failed to clean {}", path.display()))?;
            } else {
                fs::remove_file(&path)
                    .with_context(|| format!("failed to clean {}", path.display()))?;
            }
        }
    }
    fs::create_dir_all(dist_dir.join("src"))
        .with_context(|| format!("failed to create {}", dist_dir.display()))?;

    fs::write(dist_dir.join("Cargo.toml"), render_cargo_toml(manifest))?;
    fs::write(dist_dir.join("src").join("main.rs"), render_main_rs(manifest)?)?;
    Ok(())
}

fn render_cargo_toml(manifest: &Manifest) -> String {
    let mut deps = String::from(
        "axum = \"0.8\"\n\
         tokio = { version = \"1\", features = [\"macros\", \"rt-multi-thread\"] }\n\
         anyhow = \"1\"\n\
         futures-util = \"0.3\"\n",
    );
    if manifest.services.postgres.is_some() {
        deps.push_str(
            "sqlx = { version = \"0.8\", default-features = false, features = [\"runtime-tokio\", \"tls-rustls\", \"postgres\"] }\n",
        );
    }
    if manifest.services.redis.is_some() {
        deps.push_str(
            "deadpool-redis = { version = \"0.18\", features = [\"rt_tokio_1\"] }\n",
        );
    }

    format!(
        "# Generated by rublocks. Do not edit by hand.\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         \n\
         [dependencies]\n\
         {deps}",
        name = manifest.name,
    )
}

fn render_main_rs(manifest: &Manifest) -> Result<String> {
    let has_pg = manifest.services.postgres.is_some();
    let has_redis = manifest.services.redis.is_some();

    let pg_field = has_pg.then(|| quote! { pub pg: sqlx::PgPool, });
    let redis_field = has_redis.then(|| quote! { pub redis: deadpool_redis::Pool, });

    let pg_init = manifest.services.postgres.as_ref().map(|svc| {
        let url = url_expr(&svc.url);
        quote! {
            let pg = sqlx::PgPool::connect(&#url).await?;
        }
    });
    let redis_init = manifest.services.redis.as_ref().map(|svc| {
        let url = url_expr(&svc.url);
        quote! {
            let redis = deadpool_redis::Config::from_url(&#url)
                .create_pool(Some(deadpool_redis::Runtime::Tokio1))?;
        }
    });

    let pg_state = has_pg.then(|| quote! { pg, });
    let redis_state = has_redis.then(|| quote! { redis, });

    let dev_index_html = render_dev_index_html(&manifest.name);

    let tokens = quote! {
        use axum::{routing::get, Router};

        #[derive(Clone)]
        pub struct AppState {
            #pg_field
            #redis_field
        }

        #[tokio::main]
        async fn main() -> anyhow::Result<()> {
            #pg_init
            #redis_init

            let state = AppState {
                #pg_state
                #redis_state
            };

            let mut router = Router::new().route("/health", get(health));

            if std::env::var("RUBLOCKS_DEV").is_ok() {
                router = router
                    .route("/", get(dev_index))
                    .route("/__rublocks/livereload.js", get(dev_snippet))
                    .route("/__rublocks/events", get(dev_events));
                eprintln!("rublocks: dev endpoints enabled at /, /__rublocks/*");
            }

            let app = router.with_state(state);

            let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await?;
            println!("rublocks app listening on http://0.0.0.0:3000");
            axum::serve(listener, app).await?;
            Ok(())
        }

        async fn health() -> &'static str {
            "ok"
        }

        async fn dev_index() -> axum::response::Html<&'static str> {
            axum::response::Html(#dev_index_html)
        }

        async fn dev_snippet() -> impl axum::response::IntoResponse {
            (
                [(axum::http::header::CONTENT_TYPE, "application/javascript")],
                LIVERELOAD_JS,
            )
        }

        async fn dev_events() -> axum::response::Sse<
            impl futures_util::Stream<Item = Result<axum::response::sse::Event, std::convert::Infallible>>,
        > {
            let stream = futures_util::stream::pending::<
                Result<axum::response::sse::Event, std::convert::Infallible>,
            >();
            axum::response::Sse::new(stream)
                .keep_alive(axum::response::sse::KeepAlive::default())
        }

        const LIVERELOAD_JS: &str = #LIVERELOAD_JS_SOURCE;
    };

    let file: syn::File = syn::parse2(tokens).context("failed to parse generated tokens")?;
    let body = prettyplease::unparse(&file);
    Ok(format!("// Generated by rublocks. Do not edit by hand.\n\n{body}"))
}

fn url_expr(url: &ServiceUrl) -> TokenStream {
    match url {
        ServiceUrl::Literal(s) => quote! { #s.to_string() },
        ServiceUrl::Env(var) => quote! { std::env::var(#var)? },
    }
}

fn render_dev_index_html(app_name: &str) -> String {
    format!(
        "<!DOCTYPE html>\n\
         <html lang=\"en\">\n\
         <head>\n  \
           <meta charset=\"utf-8\">\n  \
           <title>{app_name} \u{2014} rublocks dev</title>\n  \
           <script src=\"/__rublocks/livereload.js\"></script>\n\
         </head>\n\
         <body style=\"font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; color: #222;\">\n  \
           <h1 style=\"margin-bottom: 0.25rem;\">{app_name}</h1>\n  \
           <p style=\"color: #666; margin-top: 0;\">rublocks dev mode</p>\n  \
           <p>Edit <code>main.json</code> and save \u{2014} this page will reload automatically.</p>\n\
         </body>\n\
         </html>\n"
    )
}

const LIVERELOAD_JS_SOURCE: &str = r#"(function () {
  let everConnected = false;
  function connect() {
    const es = new EventSource('/__rublocks/events');
    es.onopen = function () {
      if (everConnected) {
        location.reload();
      }
      everConnected = true;
    };
    es.onerror = function () {
      es.close();
      setTimeout(connect, 500);
    };
  }
  connect();
})();
"#;
