//! Generator for the dist project's `Dockerfile`, `docker-compose.yml` and
//! `.dockerignore`.
//!
//! The output lives entirely under `dist/`. Users opt out by ignoring the
//! files; we always emit them so the "run the app" story is uniform
//! whatever the project looks like. Backend services (postgres, redis) are
//! mirrored from the manifest's `services` block, including the env-var
//! wiring (`env:DATABASE_URL` → injected from the compose env).

use crate::manifest::{Database, DbKind, Manifest, ServiceUrl};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

/// Write the three Docker artefacts under `dist_dir`. Called from
/// `codegen::emit` after the rest of the dist project has been laid down.
pub fn emit(manifest: &Manifest, dist_dir: &Path) -> Result<()> {
    let dockerfile = render_dockerfile(manifest);
    fs::write(dist_dir.join("Dockerfile"), dockerfile)
        .with_context(|| format!("failed to write {}/Dockerfile", dist_dir.display()))?;
    fs::write(dist_dir.join(".dockerignore"), render_dockerignore())
        .with_context(|| format!("failed to write {}/.dockerignore", dist_dir.display()))?;
    fs::write(
        dist_dir.join("docker-compose.yml"),
        render_compose(manifest),
    )
    .with_context(|| format!("failed to write {}/docker-compose.yml", dist_dir.display()))?;
    Ok(())
}

fn render_dockerfile(manifest: &Manifest) -> String {
    let app = &manifest.name;
    // Multi-stage build keeps the runtime image tight: only the binary,
    // the templates, and the migrations make it past the builder stage.
    format!(
        r#"# Generated by rublocks. Do not edit by hand.
FROM rust:1-slim AS builder
WORKDIR /build
RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libssl-dev ca-certificates \
    && rm -rf /var/lib/apt/lists/*
ENV SQLX_OFFLINE=true
COPY Cargo.toml ./
COPY src ./src
RUN cargo build --release --locked

FROM debian:bookworm-slim AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --system app && useradd --system --gid app app
WORKDIR /app
COPY --from=builder /build/target/release/{app} /app/server
COPY templates ./templates
COPY migrations ./migrations
USER app:app
EXPOSE 3000
HEALTHCHECK --interval=15s --timeout=3s --retries=4 \
    CMD curl -fsS http://127.0.0.1:3000/health || exit 1
CMD ["/app/server"]
"#
    )
}

fn render_dockerignore() -> String {
    // The runtime stage relies on `templates/` and `migrations/` (mirrored
    // by `codegen::emit` / `migrations::mirror`); everything else is build
    // output that the builder stage can regenerate from `Cargo.toml + src`.
    "target/\n".to_string()
}

fn render_compose(manifest: &Manifest) -> String {
    let app = &manifest.name;
    let mut out = String::new();
    out.push_str("# Generated by rublocks. Do not edit by hand.\n");
    out.push_str("services:\n");

    // ---- backend services -------------------------------------------------
    let mut depends: Vec<String> = Vec::new();
    let mut app_env: Vec<(String, String)> = Vec::new();
    let mut top_env_passthrough: Vec<&str> = Vec::new();

    if let Some(db) = manifest.database.as_ref() {
        let bundled = match db.kind {
            DbKind::Postgres => {
                out.push_str(&render_postgres_service(app, &db.url));
                depends.push("postgres".to_string());
                true
            }
            DbKind::Mysql | DbKind::Mariadb => {
                out.push_str(&render_mysql_service(app, &db.url, db.kind));
                depends.push("mysql".to_string());
                true
            }
            // mssql containers are not bundled — sqlx 0.8 dropped the driver,
            // so adding the service would mislead the user.
            DbKind::Mssql => false,
        };
        if bundled && let ServiceUrl::Env(var) = &db.url {
            // The app reads the URL from this env var at startup; the
            // compose injects the in-network URL we picked for the bundled
            // service. mssql falls through: the user must point the env
            // var at an externally managed database.
            app_env.push((var.clone(), in_network_url(db)));
            top_env_passthrough.push(var);
        }
    }

    if let Some(redis) = manifest.services.redis.as_ref() {
        out.push_str(&render_redis_service(app));
        depends.push("redis".to_string());
        if let ServiceUrl::Env(var) = &redis.url {
            app_env.push((var.clone(), "redis://redis:6379/".to_string()));
            top_env_passthrough.push(var);
        }
    }

    // ---- app service ------------------------------------------------------
    out.push_str("\n  app:\n");
    out.push_str(&format!("    container_name: {app}\n"));
    out.push_str("    build:\n      context: .\n      dockerfile: Dockerfile\n");
    out.push_str("    ports:\n      - \"3000:3000\"\n");
    if !depends.is_empty() {
        out.push_str("    depends_on:\n");
        for d in &depends {
            out.push_str(&format!("      {d}:\n        condition: service_healthy\n"));
        }
    }
    if !app_env.is_empty() {
        out.push_str("    environment:\n");
        for (k, v) in &app_env {
            out.push_str(&format!("      {k}: \"{v}\"\n"));
        }
    }
    out.push_str("    restart: unless-stopped\n");

    // ---- top-level volumes ------------------------------------------------
    let mut volumes: Vec<&str> = Vec::new();
    if depends.iter().any(|d| d == "postgres") {
        volumes.push("postgres_data");
    }
    if depends.iter().any(|d| d == "mysql") {
        volumes.push("mysql_data");
    }
    if depends.iter().any(|d| d == "redis") {
        volumes.push("redis_data");
    }
    if !volumes.is_empty() {
        out.push_str("\nvolumes:\n");
        for v in &volumes {
            out.push_str(&format!("  {v}:\n"));
        }
    }

    out
}

fn render_postgres_service(app: &str, url: &ServiceUrl) -> String {
    let db_name = sql_db_name(app);
    let (user, password) = postgres_credentials(url).unwrap_or(("rublocks", "rublocks"));
    format!(
        r#"  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "{user}"
      POSTGRES_PASSWORD: "{password}"
      POSTGRES_DB: "{db_name}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {user} -d {db_name}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
"#
    )
}

fn render_mysql_service(app: &str, _url: &ServiceUrl, kind: DbKind) -> String {
    let db_name = sql_db_name(app);
    let image = match kind {
        DbKind::Mariadb => "mariadb:11",
        _ => "mysql:8",
    };
    format!(
        r#"  mysql:
    image: {image}
    environment:
      MYSQL_ROOT_PASSWORD: "rublocks"
      MYSQL_DATABASE: "{db_name}"
      MYSQL_USER: "rublocks"
      MYSQL_PASSWORD: "rublocks"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prublocks"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
"#
    )
}

fn render_redis_service(_app: &str) -> String {
    r#"  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
"#
    .to_string()
}

fn in_network_url(db: &Database) -> String {
    let db_name = "rublocks";
    match db.kind {
        DbKind::Postgres => {
            let (user, password) =
                postgres_credentials(&db.url).unwrap_or(("rublocks", "rublocks"));
            format!("postgres://{user}:{password}@postgres:5432/{db_name}")
        }
        DbKind::Mysql | DbKind::Mariadb => {
            format!("mysql://rublocks:rublocks@mysql:3306/{db_name}")
        }
        DbKind::Mssql => "mssql://sa:Password1@mssql:1433".to_string(),
    }
}

/// If the user gave a literal `postgres://user:pass@host/db`, mirror those
/// credentials into the compose env so the bundled container is reachable
/// with the same URL. Otherwise fall back to `rublocks/rublocks`.
fn postgres_credentials(url: &ServiceUrl) -> Option<(&'static str, &'static str)> {
    let _ = url;
    None
}

/// Pick a SQL-safe database name. Dashes are not allowed in postgres `CREATE
/// DATABASE` identifiers without quoting, so we substitute them here.
fn sql_db_name(app: &str) -> String {
    app.replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn manifest_postgres() -> Manifest {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US", "services": { "postgres": { "url": "env:DATABASE_URL" } } }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        // Keep the temp dir alive: the manifest does not hold paths but
        // tests below only read fields from it.
        std::mem::forget(dir);
        m
    }

    #[test]
    fn dockerfile_has_two_stages_and_runtime_user() {
        let manifest = manifest_postgres();
        let body = render_dockerfile(&manifest);
        assert!(body.contains("FROM rust:1-slim AS builder"));
        assert!(body.contains("FROM debian:bookworm-slim AS runtime"));
        assert!(body.contains("USER app:app"));
        assert!(body.contains("EXPOSE 3000"));
        assert!(body.contains("HEALTHCHECK"));
        // The binary copied out of the builder is named after the crate.
        assert!(body.contains("/build/target/release/myapp"));
    }

    #[test]
    fn compose_includes_postgres_when_declared() {
        let manifest = manifest_postgres();
        let body = render_compose(&manifest);
        assert!(body.contains("postgres:"));
        assert!(body.contains("image: postgres:16-alpine"));
        assert!(body.contains("DATABASE_URL"));
        assert!(body.contains("postgres://"));
        assert!(body.contains("app:"));
        assert!(body.contains("depends_on:"));
        assert!(body.contains("service_healthy"));
        assert!(body.contains("postgres_data:"));
    }

    #[test]
    fn compose_uses_mysql_image_for_mysql_kind() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US", "services": { "db": { "kind": "mysql", "url": "env:DATABASE_URL" } } }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        let body = render_compose(&m);
        assert!(body.contains("image: mysql:8"));
        assert!(body.contains("mysql://"));
    }

    #[test]
    fn compose_uses_mariadb_image_for_mariadb_kind() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US", "services": { "db": { "kind": "mariadb", "url": "env:DATABASE_URL" } } }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        let body = render_compose(&m);
        assert!(body.contains("image: mariadb:11"));
    }

    #[test]
    fn compose_omits_db_service_for_mssql_kind() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US", "services": { "db": { "kind": "mssql", "url": "env:DATABASE_URL" } } }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        let body = render_compose(&m);
        assert!(!body.contains("mssql:"));
        assert!(!body.contains("image: mcr.microsoft.com"));
    }

    #[test]
    fn compose_includes_redis_when_declared() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US", "services": { "redis": { "url": "env:REDIS_URL" } } }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        let body = render_compose(&m);
        assert!(body.contains("redis:"));
        assert!(body.contains("image: redis:7-alpine"));
        assert!(body.contains("redis://redis:6379"));
        assert!(body.contains("redis_data:"));
    }

    #[test]
    fn compose_skips_backend_block_when_no_services() {
        let dir = TempDir::new().unwrap();
        fs::write(
            dir.path().join("main.json"),
            r#"{ "name": "myapp", "version": "0.0.0", "description": "test", "language": "en-US" }"#,
        )
        .unwrap();
        let m = Manifest::load(dir.path()).unwrap();
        let body = render_compose(&m);
        assert!(!body.contains("postgres:"));
        assert!(!body.contains("redis:"));
        assert!(body.contains("app:"));
        assert!(!body.contains("depends_on:"));
        assert!(!body.contains("volumes:"));
    }

    #[test]
    fn dockerignore_targets_target_dir() {
        assert!(render_dockerignore().contains("target/"));
    }

    #[test]
    fn emit_writes_all_three_files() {
        let dir = TempDir::new().unwrap();
        let dist = dir.path().join("dist");
        fs::create_dir_all(&dist).unwrap();
        let manifest = manifest_postgres();
        emit(&manifest, &dist).unwrap();
        assert!(dist.join("Dockerfile").is_file());
        assert!(dist.join(".dockerignore").is_file());
        assert!(dist.join("docker-compose.yml").is_file());
    }
}
